### ISSUE TITLE
Rebranding to Kentico Kontent

### ISSUE THREAD

**Issue by petrsvihlik** [Simply007/kontent-template-gatsby-landing-page-photon#3]
Hi @Simply007 !
We've just renamed Kentico Cloud to [Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent). We are in the process of renaming all SDKs, developer tools, and sample apps. Please consider renaming your plugin (code: namespaces, classes; repo, wiki, GH topics, etc.) to Kentico Kontent. See the guidelines at https://gitter.im/Kentico/Kontent?at=5d8b643d692d464f7969c6d9.

Thanks!

**Comment by Simply007** [comment]
Done
